node {
   def commit_id
   stage('Preparation') {
     checkout scm
     sh "git rev-parse --short HEAD > .git/commit-id"                        
     commit_id = readFile('.git/commit-id').trim()
   }
   stage('test') {
     nodejs(nodeJSInstallationName: 'nodejs') {
       sh 'npm install --only=dev'
       sh 'npm test'
     }
   }
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("mvangeepuram/nodejs:${commit_id}", '.').push()
 
   }
   }
   
   stage('docker build/push') {
     docker.withRegistry('https://index.docker.io/v1/', 'dockerhub') {
       def app = docker.build("mvangeepuram/nodejs:${commit_id}", '.').push()
     }
   } 
        
   stage('docker post deploy /validation') {
      docker.image('mvangeepuram/nodejs').run{c ->
         
         
        }
           
           docker.image('mvangeepuram/nodejs').inside("-p 3000:3000 --link ${c.id}:node") {
            /* sh 'curl -L http://localhost:3000/' */
             sh "/usr/bin/docker logs ${c.id}"
        }
           
      }
   }
}

